import { Layout } from "@/components/layout";
import "@/styles/globals.css";
import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" suppressHydrationWarning={true}>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
